export const colors = {
  headfoot: '#F6F7EB',
  headfootbutton: 'grey',
  headfootbuttontext: 'black',
  tintcolor: 'white',
};

export const env = {
  version: '1.0',
};

export const timezonesData = [
  { location: 'Aberdeen, Scotland', timezone: 'GMT' },
  { location: 'Adelaide, Australia', timezone: 'GMT +09:30' },
  { location: 'Albuquerque, N.M.', timezone: 'GMT -06:00' },
  { location: 'Atlanta, Ga.', timezone: 'GMT -04:00' },
  { location: 'Auckland, New Zealand', timezone: 'GMT +13:00' },
  { location: 'Baghdad', timezone: 'GMT +03:00' },
  { location: 'Baltimore, Md.', timezone: 'GMT -05:00' },
  { location: 'Bangalore', timezone: 'GMT +05:30' },
  { location: 'Bangkok, Thailand', timezone: 'GMT +07:00' },
  { location: 'Barcelona, Spain', timezone: 'GMT +01:00' },
  { location: 'Beijing, China', timezone: 'GMT +08:00' },
  { location: 'Cairns', timezone: 'GMT +10:00' },
  { location: 'Calgary, Alba., Can.', timezone: 'GMT -06:00' },
  { location: 'Canberra', timezone: 'GMT +11:00' },
  { location: 'Caracas, Venezuela', timezone: 'GMT -04:00' },
  { location: 'Cardobas', timezone: 'GMT -03:00' },
  { location: 'Chicago, Ill.', timezone: 'GMT -06:00' },
  { location: 'Dakar, Senegal', timezone: 'GMT' },
  { location: 'Dallas, Tex.', timezone: 'GMT -06:00' },
  { location: 'Darwin, Australia', timezone: 'GMT +09:30' },
  { location: 'Denpasar', timezone: 'GMT +08:00' },
  { location: 'Detroit, Mich.', timezone: 'GMT -05:00' },
  { location: 'Dhaka', timezone: 'GMT +06:00' },
  { location: 'Easter Island', timezone: 'GMT -06:00' },
  { location: 'Edinburgh, Scotland', timezone: 'GMT' },
  { location: 'El Centro, Calif.', timezone: 'GMT -08:00' },
  { location: 'Eucla', timezone: 'GMT +08:45' },
  { location: 'Eugene, Ore.', timezone: 'GMT -08:00' },
  { location: 'Frankfurt, Germany', timezone: 'GMT +01:00' },
  { location: 'Glasgow, Scotland', timezone: 'GMT' },
  { location: 'Grand Junction, Colo.', timezone: 'GMT -07:00' },
  { location: 'Grand Rapids, Mich.', timezone: 'GMT -05:00' },
  { location: 'Guatemala', timezone: 'GMT -06:00' },
  { location: 'Guayaquil, Ecuador', timezone: 'GMT -05:00' },
  { location: 'Halifax', timezone: 'GMT -04:00' },
  { location: 'Hamburg, Germany', timezone: 'GMT +01:00' },
  { location: 'Hamilton', timezone: 'GMT -05:00' },
  { location: 'Hammerfest, Norway', timezone: 'GMT +01:00' },
  { location: 'Hanoi', timezone: 'GMT +07:00' },
  { location: 'Hovd', timezone: 'GMT +07:00' },
  { location: 'Idaho Falls, Idaho', timezone: 'GMT -07:00' },
  { location: 'Indianapolis, Ind.', timezone: 'GMT -05:00' },
  { location: 'Inuvik', timezone: 'GMT -07:00' },
  { location: 'Iquique, Chile', timezone: 'GMT -04:00' },
  { location: 'Irkutsk, Russia', timezone: 'GMT +08:00' },
  { location: 'Islamabad', timezone: 'GMT +05:00' },
  { location: 'Jerusalem', timezone: 'GMT +02:00' },
  { location: 'Johannesburg, South Africa', timezone: 'GMT +02:00' },
  { location: 'Juba', timezone: 'GMT +03:00' },
  { location: 'Juneau, Alaska', timezone: 'GMT -09:00' },
  { location: 'Kabul', timezone: 'GMT +04:30' },
  { location: 'Kampala', timezone: 'GMT +03:00' },
  { location: 'Kansas City', timezone: 'GMT -06:00' },
  { location: 'Karachi', timezone: 'GMT +05:00' },
  { location: 'Kathmandu', timezone: 'GMT +05:45' },
  { location: 'Lagos', timezone: 'GMT +01:00' },
  { location: 'Lahore', timezone: 'GMT +05:00' },
  { location: 'Las Vegas, Nev.', timezone: 'GMT -08:00' },
  { location: 'Leeds, England', timezone: 'GMT' },
  { location: 'Liverpool, England', timezone: 'GMT' },
  { location: 'London, England', timezone: 'GMT' },
  { location: 'London, Ont., Can.', timezone: 'GMT -05:00' },
  { location: 'Long Beach, Calif.', timezone: 'GMT -08:00' },
  { location: 'Longyearbyen', timezone: 'GMT +01:00' },
  { location: 'Luxembourg', timezone: 'GMT +01:00' },
  { location: 'Lyons, France', timezone: 'GMT +01:00' },
  { location: 'Madrid, Spain', timezone: 'GMT +01:00' },
  { location: 'Magadan', timezone: 'GMT +11:00' },
  { location: 'Majuro', timezone: 'GMT +12:00' },
  { location: 'Manchester, England', timezone: 'GMT' },
  { location: 'Melbourne, Australia', timezone: 'GMT +11:00' },
  { location: 'Memphis, Tenn.', timezone: 'GMT -06:00' },
  { location: 'Mexico City, Mexico', timezone: 'GMT -06:00' },
  { location: 'Mumbai, India', timezone: 'GMT +05:30' },
  { location: 'Nagasaki, Japan', timezone: 'GMT +09:00' },
  { location: 'Nagoya, Japan', timezone: 'GMT +09:00' },
  { location: 'Nairobi, Kenya', timezone: 'GMT +03:00' },
  { location: 'Nanjing (Nanking), China', timezone: 'GMT +08:00' },
  { location: 'Nashville, Tenn.', timezone: 'GMT -06:00' },
  { location: 'Nassau', timezone: 'GMT -05:00' },
  { location: 'Oakland, Calif.', timezone: 'GMT -08:00' },
  { location: 'Odessa, Ukraine', timezone: 'GMT +02:00' },
  { location: 'Oklahoma City, Okla.', timezone: 'GMT -06:00' },
  { location: 'Omaha, Neb.', timezone: 'GMT -06:00' },
  { location: 'Omsk', timezone: 'GMT +06:00' },
  { location: 'Oral', timezone: 'GMT +05:00' },
  { location: 'Osaka, Japan', timezone: 'GMT +09:00' },
  { location: 'Panama City, Panama', timezone: 'GMT -05:00' },
  { location: 'Paramaribo', timezone: 'GMT -03:00' },
  { location: 'Paris, France', timezone: 'GMT +01:00' },
  { location: 'Perth, Australia', timezone: 'GMT +08:00' },
  { location: 'Philadelphia, Pa.', timezone: 'GMT -05:00' },
  { location: 'Phnom Penh', timezone: 'GMT +07:00' },
  { location: 'Phoenix, Ariz.', timezone: 'GMT -07:00' },
  { location: 'Pyongyang', timezone: 'GMT +09:00' },
  { location: 'Quebec, Que., Can.', timezone: 'GMT -05:00' },
  { location: 'Raleigh, N.C.', timezone: 'GMT -05:00' },
  { location: 'Rangoon, Myanmar', timezone: 'GMT +06:30' },
  { location: 'Reno, Nev.', timezone: 'GMT -08:00' },
  { location: 'Resolute Bay', timezone: 'GMT -06:00' },
  { location: 'Reykjavik, Iceland', timezone: 'GMT' },
  { location: 'Richmond, Va.', timezone: 'GMT -05:00' },
  { location: 'Riga', timezone: 'GMT +02:00' },
  { location: 'Rio Branco', timezone: 'GMT -05:00' },
  { location: 'Rio de Janeiro, Brazil', timezone: 'GMT -03:00' },
  { location: 'Sacramento, Calif.', timezone: 'GMT -08:00' },
  { location: 'Salt Lake City, Utah', timezone: 'GMT -07:00' },
  { location: 'Salvador, Brazil', timezone: 'GMT -03:00' },
  { location: 'San Antonio, Tex.', timezone: 'GMT -06:00' },
  { location: 'San Diego, Calif.', timezone: 'GMT -08:00' },
  { location: 'Seoul', timezone: 'GMT +09:00' },
  { location: 'St. Petersburg, Russia', timezone: 'GMT +03:00' },
  { location: 'Taipei', timezone: 'GMT +08:00' },
  { location: 'Tallinn', timezone: 'GMT +02:00' },
  { location: 'Tampa, Fla.', timezone: 'GMT -05:00' },
  { location: 'Tananarive, Madagascar', timezone: 'GMT +03:00' },
  { location: 'Tarawa', timezone: 'GMT +12:00' },
  { location: 'Tashkent', timezone: 'GMT +05:00' },
  { location: 'Tbilisi', timezone: 'GMT +04:00' },
  { location: 'Thule Air Base', timezone: 'GMT -04:00' },
  { location: 'Tokyo, Japan', timezone: 'GMT +09:00' },
  { location: 'Ulaanbaatar', timezone: 'GMT +08:00' },
  { location: 'Urumqi', timezone: 'GMT +06:00' },
  { location: 'Vatican City', timezone: 'GMT +01:00' },
  { location: 'Victoria, B.C., Can.', timezone: 'GMT -08:00' },
  { location: 'Vienna, Austria', timezone: 'GMT +01:00' },
  { location: 'Vientiane', timezone: 'GMT +07:00' },
  { location: 'Vladivostok, Russia', timezone: 'GMT +10:00' },
  { location: 'Wellington, New Zealand', timezone: 'GMT +13:00' },
  { location: 'Whitehorse', timezone: 'GMT -08:00' },
  { location: 'Wichita, Kan.', timezone: 'GMT -06:00' },
  { location: 'Wilmington, N.C.', timezone: 'GMT -05:00' },
  { location: 'Winnipeg, Man., Can.', timezone: 'GMT -06:00' },
  { location: 'Yakutsk', timezone: 'GMT +09:00' },
  { location: 'Yekaterinburg', timezone: 'GMT +05:00' },
  { location: 'Yerevan', timezone: 'GMT +04:00' },
  { location: 'Zagreb', timezone: 'GMT +01:00' },
  { location: 'Zurich, Switzerland', timezone: 'GMT +01:00' },
  { location: 'Chicago', timezone: 'GMT - 05:00' },
  { location: 'New York', timezone: 'GMT - 05:00' },
  { location: 'Los Angeles', timezone: 'GMT - 07:00' },
  { location: 'London', timezone: 'GMT + 00:00' },
  { location: 'Paris', timezone: 'GMT + 01:00' },
  { location: 'Tokyo', timezone: 'GMT + 09:00' },
  { location: 'Sydney', timezone: 'GMT + 11:00' },
  { location: 'Berlin', timezone: 'GMT + 01:00' },
  { location: 'Beijing', timezone: 'GMT + 08:00' },
  { location: 'Moscow', timezone: 'GMT + 03:00' },
  { location: 'Dubai', timezone: 'GMT + 04:00' },
  { location: 'Toronto', timezone: 'GMT - 05:00' },
  { location: 'Singapore', timezone: 'GMT + 08:00' },
  { location: 'Mumbai', timezone: 'GMT + 05:30' },
  { location: 'Johannesburg', timezone: 'GMT + 02:00' },
  { location: 'Auckland', timezone: 'GMT + 12:00' },
  { location: 'Sao Paulo', timezone: 'GMT - 03:00' },
  { location: 'Vancouver', timezone: 'GMT - 07:00' },
  { location: 'Cairo', timezone: 'GMT + 02:00' },
  { location: 'Mexico City', timezone: 'GMT - 06:00' },
  { location: 'New Delhi', timezone: 'GMT + 05:30' },
  { location: 'Toronto', timezone: 'GMT - 05:00' },
  { location: 'Seoul', timezone: 'GMT + 09:00' },
  { location: 'Madrid', timezone: 'GMT + 01:00' },
  { location: 'Rome', timezone: 'GMT + 01:00' },
  { location: 'Hong Kong', timezone: 'GMT + 08:00' },
  { location: 'Athens', timezone: 'GMT + 02:00' },
  { location: 'Amsterdam', timezone: 'GMT + 01:00' },
  { location: 'Stockholm', timezone: 'GMT + 01:00' },
  { location: 'Bangkok', timezone: 'GMT + 07:00' },
  { location: 'Osaka', timezone: 'GMT + 09:00' },
  { location: 'Montreal', timezone: 'GMT - 05:00' },
  { location: 'Barcelona', timezone: 'GMT + 01:00' },
  { location: 'Lisbon', timezone: 'GMT' },
  { location: 'Prague', timezone: 'GMT + 01:00' },
  { location: 'Vienna', timezone: 'GMT + 01:00' },
  { location: 'Brussels', timezone: 'GMT + 01:00' },
  { location: 'Milan', timezone: 'GMT + 01:00' },
  { location: 'Toronto', timezone: 'GMT - 05:00' },
  { location: 'Warsaw', timezone: 'GMT + 01:00' },
  { location: 'Helsinki', timezone: 'GMT + 02:00' },
  { location: 'Manchester', timezone: 'GMT' },
  { location: 'Budapest', timezone: 'GMT + 01:00' },
  { location: 'Bucharest', timezone: 'GMT + 02:00' },
  { location: 'Hamburg', timezone: 'GMT + 01:00' },
  { location: 'St. Petersburg', timezone: 'GMT + 03:00' },
  { location: 'Dublin', timezone: 'GMT' },
  { location: 'Athens', timezone: 'GMT + 02:00' },
  { location: 'Leeds', timezone: 'GMT' },
  { location: 'Barcelona', timezone: 'GMT + 01:00' },
  { location: 'Warsaw', timezone: 'GMT + 01:00' },
  { location: 'Vienna', timezone: 'GMT + 01:00' },
  { location: 'Munich', timezone: 'GMT + 01:00' },
  { location: 'Lisbon', timezone: 'GMT' },
  { location: 'Rome', timezone: 'GMT + 01:00' },
  { location: 'Milan', timezone: 'GMT + 01:00' },
  { location: 'Athens', timezone: 'GMT + 02:00' },
  { location: 'Naples', timezone: 'GMT + 01:00' },
  { location: 'Krakow', timezone: 'GMT + 01:00' },
  { location: 'Wroclaw', timezone: 'GMT + 01:00' },
  { location: 'Sofia', timezone: 'GMT + 02:00' },
  { location: 'Ljubljana', timezone: 'GMT + 01:00' },
  { location: 'Lyon', timezone: 'GMT + 01:00' },
  { location: 'Manchester', timezone: 'GMT' },
  { location: 'Birmingham', timezone: 'GMT' },
  { location: 'Glasgow', timezone: 'GMT' },
  { location: 'Sheffield', timezone: 'GMT' },
  { location: 'Dublin', timezone: 'GMT' },
  { location: 'Marseille', timezone: 'GMT + 01:00' },
  { location: 'Krakow', timezone: 'GMT + 01:00' },
  { location: 'Amsterdam', timezone: 'GMT + 01:00' },
  { location: 'Rotterdam', timezone: 'GMT + 01:00' },
  { location: 'The Hague', timezone: 'GMT + 01:00' },
  { location: 'Utrecht', timezone: 'GMT + 01:00' },
  { location: 'Leiden', timezone: 'GMT + 01:00' },
  { location: 'Groningen', timezone: 'GMT + 01:00' },
  { location: 'Eindhoven', timezone: 'GMT + 01:00' },
  { location: 'Nijmegen', timezone: 'GMT + 01:00' },
  { location: 'Arnhem', timezone: 'GMT + 01:00' },
  { location: 'Amersfoort', timezone: 'GMT + 01:00' },
  { location: 'Apeldoorn', timezone: 'GMT + 01:00' },
  { location: 'Zwolle', timezone: 'GMT + 01:00' },
  { location: 'Leeuwarden', timezone: 'GMT + 01:00' },
  { location: 'Groningen', timezone: 'GMT + 01:00' },
  { location: 'Enschede', timezone: 'GMT + 01:00' },
  { location: 'Maastricht', timezone: 'GMT + 01:00' },
  { location: 'Eindhoven', timezone: 'GMT + 01:00' },
  { location: 'Tilburg', timezone: 'GMT + 01:00' },
  { location: 'Breda', timezone: 'GMT + 01:00' },
  { location: 'Rotterdam', timezone: 'GMT + 01:00' },
  { location: 'The Hague', timezone: 'GMT + 01:00' },
  { location: 'Utrecht', timezone: 'GMT + 01:00' },
  { location: 'Leiden', timezone: 'GMT + 01:00' },
  { location: 'Amersfoort', timezone: 'GMT + 01:00' },
  { location: 'Apeldoorn', timezone: 'GMT + 01:00' },
  { location: 'Nijmegen', timezone: 'GMT + 01:00' },
  { location: 'Arnhem', timezone: 'GMT + 01:00' },
  { location: 'Amsterdam', timezone: 'GMT + 01:00' },
  { location: 'Groningen', timezone: 'GMT + 01:00' },
  { location: 'Utrecht', timezone: 'GMT + 01:00' },
];
