/* eslint-disable prettier/prettier */
export const lang = [
  {
    appname: 'World Clocks/Time Convertor',
    label: 'Select Language',
    selectlanguage: 'Select Language',
    default: 'Default',
    save: 'Save',
    reset: 'Reset',
    help: 'Help',
    Ok: 'Ok',
    home: 'Home',
    edit: 'Edit',
    helphead: 'Welcome to the World Clock',
    more: 'More Apps',
    web: 'Web Apps',
    tnc: 'Apps Policy',
    info: 'About',
    share: 'Share',
    settings: 'Settings',
    appshead: 'Apps Privacy Policy',
    cancel: 'Cancel',
    dismiss: 'Dismiss',
    clocks: 'Clocks',
    conv: 'Convertor',
    setzone: 'Set Zone',
    thiscity: "This city does not 'observe' / 'is not currently observing' DST",
    nextdst: 'Next DST transition for this city occurs at your local time:',
    local: 'Local',
  },
  {appname: 'World Clocks/Time Convertor'},
  {appname: 'World Clocks/Time Convertor'},
  {appname: 'World Clocks/Time Convertor'},
  {appname: 'World Clocks/Time Convertor'},
  {appname: 'World Clocks/Time Convertor'},
  {appname: 'World Clocks/Time Convertor'},
];
