/* eslint-disable prettier/prettier */

export const colors = {
  headfoot: '#F6F7EB',
  headfootbutton: 'grey',
  headfootbuttontext: 'black',
  tintcolor: 'white',
};

export const env = {
  version: '1.0',
};

export const timezonesData = [
  {location: 'Chicago', timezone: 'GMT - 05:00'},
  {location: 'New York', timezone: 'GMT - 05:00'},
  {location: 'Los Angeles', timezone: 'GMT - 07:00'},
  {location: 'London', timezone: 'GMT + 00:00'},
  {location: 'Paris', timezone: 'GMT + 01:00'},
  {location: 'Tokyo', timezone: 'GMT + 09:00'},
  {location: 'Sydney', timezone: 'GMT + 11:00'},
  {location: 'Berlin', timezone: 'GMT + 01:00'},
  {location: 'Beijing', timezone: 'GMT + 08:00'},
  {location: 'Moscow', timezone: 'GMT + 03:00'},
  {location: 'Dubai', timezone: 'GMT + 04:00'},
  {location: 'Toronto', timezone: 'GMT - 05:00'},
  {location: 'Singapore', timezone: 'GMT + 08:00'},
  {location: 'Mumbai', timezone: 'GMT + 05:30'},
  {location: 'Johannesburg', timezone: 'GMT + 02:00'},
  {location: 'Auckland', timezone: 'GMT + 12:00'},
  {location: 'Sao Paulo', timezone: 'GMT - 03:00'},
  {location: 'Vancouver', timezone: 'GMT - 07:00'},
  {location: 'Cairo', timezone: 'GMT + 02:00'},
  {location: 'Mexico City', timezone: 'GMT - 06:00'},
  {location: 'New Delhi', timezone: 'GMT + 05:30'},
  {location: 'Toronto', timezone: 'GMT - 05:00'},
  {location: 'Seoul', timezone: 'GMT + 09:00'},
  {location: 'Madrid', timezone: 'GMT + 01:00'},
  {location: 'Rome', timezone: 'GMT + 01:00'},
  {location: 'Hong Kong', timezone: 'GMT + 08:00'},
  {location: 'Athens', timezone: 'GMT + 02:00'},
  {location: 'Amsterdam', timezone: 'GMT + 01:00'},
  {location: 'Stockholm', timezone: 'GMT + 01:00'},
  {location: 'Bangkok', timezone: 'GMT + 07:00'},
  {location: 'Osaka', timezone: 'GMT + 09:00'},
  {location: 'Montreal', timezone: 'GMT - 05:00'},
  {location: 'Barcelona', timezone: 'GMT + 01:00'},
  {location: 'Lisbon', timezone: 'GMT'},
  {location: 'Prague', timezone: 'GMT + 01:00'},
  {location: 'Vienna', timezone: 'GMT + 01:00'},
  {location: 'Brussels', timezone: 'GMT + 01:00'},
  {location: 'Milan', timezone: 'GMT + 01:00'},
  {location: 'Toronto', timezone: 'GMT - 05:00'},
  {location: 'Warsaw', timezone: 'GMT + 01:00'},
  {location: 'Helsinki', timezone: 'GMT + 02:00'},
  {location: 'Manchester', timezone: 'GMT'},
  {location: 'Budapest', timezone: 'GMT + 01:00'},
  {location: 'Bucharest', timezone: 'GMT + 02:00'},
  {location: 'Hamburg', timezone: 'GMT + 01:00'},
  {location: 'St. Petersburg', timezone: 'GMT + 03:00'},
  {location: 'Dublin', timezone: 'GMT'},
  {location: 'Athens', timezone: 'GMT + 02:00'},
  {location: 'Leeds', timezone: 'GMT'},
  {location: 'Barcelona', timezone: 'GMT + 01:00'},
  {location: 'Warsaw', timezone: 'GMT + 01:00'},
  {location: 'Vienna', timezone: 'GMT + 01:00'},
  {location: 'Munich', timezone: 'GMT + 01:00'},
  {location: 'Lisbon', timezone: 'GMT'},
  {location: 'Rome', timezone: 'GMT + 01:00'},
  {location: 'Milan', timezone: 'GMT + 01:00'},
  {location: 'Athens', timezone: 'GMT + 02:00'},
  {location: 'Naples', timezone: 'GMT + 01:00'},
  {location: 'Krakow', timezone: 'GMT + 01:00'},
  {location: 'Wroclaw', timezone: 'GMT + 01:00'},
  {location: 'Sofia', timezone: 'GMT + 02:00'},
  {location: 'Ljubljana', timezone: 'GMT + 01:00'},
  {location: 'Lyon', timezone: 'GMT + 01:00'},
  {location: 'Manchester', timezone: 'GMT'},
  {location: 'Birmingham', timezone: 'GMT'},
  {location: 'Glasgow', timezone: 'GMT'},
  {location: 'Sheffield', timezone: 'GMT'},
  {location: 'Dublin', timezone: 'GMT'},
  {location: 'Marseille', timezone: 'GMT + 01:00'},
  {location: 'Krakow', timezone: 'GMT + 01:00'},
  {location: 'Amsterdam', timezone: 'GMT + 01:00'},
  {location: 'Rotterdam', timezone: 'GMT + 01:00'},
  {location: 'The Hague', timezone: 'GMT + 01:00'},
  {location: 'Utrecht', timezone: 'GMT + 01:00'},
  {location: 'Leiden', timezone: 'GMT + 01:00'},
  {location: 'Groningen', timezone: 'GMT + 01:00'},
  {location: 'Eindhoven', timezone: 'GMT + 01:00'},
  {location: 'Nijmegen', timezone: 'GMT + 01:00'},
  {location: 'Arnhem', timezone: 'GMT + 01:00'},
  {location: 'Amersfoort', timezone: 'GMT + 01:00'},
  {location: 'Apeldoorn', timezone: 'GMT + 01:00'},
  {location: 'Zwolle', timezone: 'GMT + 01:00'},
  {location: 'Leeuwarden', timezone: 'GMT + 01:00'},
  {location: 'Groningen', timezone: 'GMT + 01:00'},
  {location: 'Enschede', timezone: 'GMT + 01:00'},
  {location: 'Maastricht', timezone: 'GMT + 01:00'},
  {location: 'Eindhoven', timezone: 'GMT + 01:00'},
  {location: 'Tilburg', timezone: 'GMT + 01:00'},
  {location: 'Breda', timezone: 'GMT + 01:00'},
  {location: 'Rotterdam', timezone: 'GMT + 01:00'},
  {location: 'The Hague', timezone: 'GMT + 01:00'},
  {location: 'Utrecht', timezone: 'GMT + 01:00'},
  {location: 'Leiden', timezone: 'GMT + 01:00'},
  {location: 'Amersfoort', timezone: 'GMT + 01:00'},
  {location: 'Apeldoorn', timezone: 'GMT + 01:00'},
  {location: 'Nijmegen', timezone: 'GMT + 01:00'},
  {location: 'Arnhem', timezone: 'GMT + 01:00'},
  {location: 'Amsterdam', timezone: 'GMT + 01:00'},
  {location: 'Groningen', timezone: 'GMT + 01:00'},
  {location: 'Utrecht', timezone: 'GMT + 01:00'},
];
